### ISSUE TITLE
玩家通过地狱门会被传送到地狱门顶部

### ISSUE THREAD

**Issue by MCsentic** [Vlvxingze/EscapeLag#20]
安装插件之后 经过地狱门传送的时候 会站在地狱门最顶部的可站立方块 而不是像原来那样站在地狱门中

**Comment by Vlvxingze** [comment]
呃？？这个我没有啊，很奇怪
你可以加我QQ，我会去尝试解决和测试的

**Comment by Vlvxingze** [comment]
经测试，该BUG不存在！
感谢你的反馈，如果你确定BUG存在，来我的QQ
