### ISSUE TITLE
未完全删除作者信息

### ISSUE THREAD

**Issue by mousesrc** [Vlvxingze/EscapeLag#21]
src/com/mcml/space/monitor/inject/IInjector.java
src/com/mcml/space/monitor/inject/AbstractInjector.java
src/com/mcml/space/patch/AntiBreakUsingChest.java
src/com/mcml/space/patch/SkullCrashPatch.java
src/com/mcml/space/monitor/PluginRecord.java
src/com/mcml/space/monitor/inject/AbstractMultipleInjector.java
src/com/mcml/space/patch/AntiDupeDropItem.java
src/com/mcml/space/monitor/MonitorRecord.java
src/com/mcml/space/monitor/inject/EventExecutorInjector.java
src/com/mcml/space/monitor/inject/SchedulerTaskInjector.java
src/com/mcml/space/monitor/inject/CommandInjector.java
src/com/mcml/space/monitor/MonitorUtils.java
等文件中均有未删除的作者信息

**Comment by andylizi** [comment]
这些如果删除了，那可就有意思了。

**Comment by mousesrc** [comment]
https://github.com/Vlvxingze/EscapeLag/commit/fb695cdb4f4e0f60d8eedb971924ea74540b8960

**Comment by Vlvxingze** [comment]
啧啧，这说明什么

**Comment by allenlol** [comment]
static abuse
这个Project🐂🍺
